/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeacherImport } from './routes/_teacher'
import { Route as StudentImport } from './routes/_student'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TeacherTeacherDashboardIndexLazyImport = createFileRoute(
  '/_teacher/teacher-dashboard/',
)()
const StudentStudentDashboardIndexLazyImport = createFileRoute(
  '/_student/student-dashboard/',
)()
const TeacherTeacherDashboardSubjectLazyImport = createFileRoute(
  '/_teacher/teacher-dashboard/subject',
)()
const TeacherTeacherDashboardClassScheduleLazyImport = createFileRoute(
  '/_teacher/teacher-dashboard/class-schedule',
)()
const TeacherTeacherDashboardAttendanceLazyImport = createFileRoute(
  '/_teacher/teacher-dashboard/attendance',
)()
const TeacherTeacherDashboardSubjectOfferingSubjectIdLazyImport =
  createFileRoute('/_teacher/teacher-dashboard/subject-offering/$subjectId')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const TeacherRoute = TeacherImport.update({
  id: '/_teacher',
  getParentRoute: () => rootRoute,
} as any)

const StudentRoute = StudentImport.update({
  id: '/_student',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeacherTeacherDashboardIndexLazyRoute =
  TeacherTeacherDashboardIndexLazyImport.update({
    path: '/teacher-dashboard/',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/teacher-dashboard/index.lazy').then(
      (d) => d.Route,
    ),
  )

const StudentStudentDashboardIndexLazyRoute =
  StudentStudentDashboardIndexLazyImport.update({
    path: '/student-dashboard/',
    getParentRoute: () => StudentRoute,
  } as any).lazy(() =>
    import('./routes/_student/student-dashboard/index.lazy').then(
      (d) => d.Route,
    ),
  )

const TeacherTeacherDashboardSubjectLazyRoute =
  TeacherTeacherDashboardSubjectLazyImport.update({
    path: '/teacher-dashboard/subject',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/teacher-dashboard/subject.lazy').then(
      (d) => d.Route,
    ),
  )

const TeacherTeacherDashboardClassScheduleLazyRoute =
  TeacherTeacherDashboardClassScheduleLazyImport.update({
    path: '/teacher-dashboard/class-schedule',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/teacher-dashboard/class-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const TeacherTeacherDashboardAttendanceLazyRoute =
  TeacherTeacherDashboardAttendanceLazyImport.update({
    path: '/teacher-dashboard/attendance',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/teacher-dashboard/attendance.lazy').then(
      (d) => d.Route,
    ),
  )

const TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute =
  TeacherTeacherDashboardSubjectOfferingSubjectIdLazyImport.update({
    path: '/teacher-dashboard/subject-offering/$subjectId',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/teacher-dashboard/subject-offering/$subjectId.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentImport
      parentRoute: typeof rootRoute
    }
    '/_teacher': {
      id: '/_teacher'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TeacherImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_teacher/teacher-dashboard/attendance': {
      id: '/_teacher/teacher-dashboard/attendance'
      path: '/teacher-dashboard/attendance'
      fullPath: '/teacher-dashboard/attendance'
      preLoaderRoute: typeof TeacherTeacherDashboardAttendanceLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_teacher/teacher-dashboard/class-schedule': {
      id: '/_teacher/teacher-dashboard/class-schedule'
      path: '/teacher-dashboard/class-schedule'
      fullPath: '/teacher-dashboard/class-schedule'
      preLoaderRoute: typeof TeacherTeacherDashboardClassScheduleLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_teacher/teacher-dashboard/subject': {
      id: '/_teacher/teacher-dashboard/subject'
      path: '/teacher-dashboard/subject'
      fullPath: '/teacher-dashboard/subject'
      preLoaderRoute: typeof TeacherTeacherDashboardSubjectLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_student/student-dashboard/': {
      id: '/_student/student-dashboard/'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentStudentDashboardIndexLazyImport
      parentRoute: typeof StudentImport
    }
    '/_teacher/teacher-dashboard/': {
      id: '/_teacher/teacher-dashboard/'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof TeacherTeacherDashboardIndexLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_teacher/teacher-dashboard/subject-offering/$subjectId': {
      id: '/_teacher/teacher-dashboard/subject-offering/$subjectId'
      path: '/teacher-dashboard/subject-offering/$subjectId'
      fullPath: '/teacher-dashboard/subject-offering/$subjectId'
      preLoaderRoute: typeof TeacherTeacherDashboardSubjectOfferingSubjectIdLazyImport
      parentRoute: typeof TeacherImport
    }
  }
}

// Create and export the route tree

interface StudentRouteChildren {
  StudentStudentDashboardIndexLazyRoute: typeof StudentStudentDashboardIndexLazyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentDashboardIndexLazyRoute: StudentStudentDashboardIndexLazyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherTeacherDashboardAttendanceLazyRoute: typeof TeacherTeacherDashboardAttendanceLazyRoute
  TeacherTeacherDashboardClassScheduleLazyRoute: typeof TeacherTeacherDashboardClassScheduleLazyRoute
  TeacherTeacherDashboardSubjectLazyRoute: typeof TeacherTeacherDashboardSubjectLazyRoute
  TeacherTeacherDashboardIndexLazyRoute: typeof TeacherTeacherDashboardIndexLazyRoute
  TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute: typeof TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherTeacherDashboardAttendanceLazyRoute:
    TeacherTeacherDashboardAttendanceLazyRoute,
  TeacherTeacherDashboardClassScheduleLazyRoute:
    TeacherTeacherDashboardClassScheduleLazyRoute,
  TeacherTeacherDashboardSubjectLazyRoute:
    TeacherTeacherDashboardSubjectLazyRoute,
  TeacherTeacherDashboardIndexLazyRoute: TeacherTeacherDashboardIndexLazyRoute,
  TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute:
    TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/teacher-dashboard/attendance': typeof TeacherTeacherDashboardAttendanceLazyRoute
  '/teacher-dashboard/class-schedule': typeof TeacherTeacherDashboardClassScheduleLazyRoute
  '/teacher-dashboard/subject': typeof TeacherTeacherDashboardSubjectLazyRoute
  '/student-dashboard': typeof StudentStudentDashboardIndexLazyRoute
  '/teacher-dashboard': typeof TeacherTeacherDashboardIndexLazyRoute
  '/teacher-dashboard/subject-offering/$subjectId': typeof TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/teacher-dashboard/attendance': typeof TeacherTeacherDashboardAttendanceLazyRoute
  '/teacher-dashboard/class-schedule': typeof TeacherTeacherDashboardClassScheduleLazyRoute
  '/teacher-dashboard/subject': typeof TeacherTeacherDashboardSubjectLazyRoute
  '/student-dashboard': typeof StudentStudentDashboardIndexLazyRoute
  '/teacher-dashboard': typeof TeacherTeacherDashboardIndexLazyRoute
  '/teacher-dashboard/subject-offering/$subjectId': typeof TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_student': typeof StudentRouteWithChildren
  '/_teacher': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_teacher/teacher-dashboard/attendance': typeof TeacherTeacherDashboardAttendanceLazyRoute
  '/_teacher/teacher-dashboard/class-schedule': typeof TeacherTeacherDashboardClassScheduleLazyRoute
  '/_teacher/teacher-dashboard/subject': typeof TeacherTeacherDashboardSubjectLazyRoute
  '/_student/student-dashboard/': typeof StudentStudentDashboardIndexLazyRoute
  '/_teacher/teacher-dashboard/': typeof TeacherTeacherDashboardIndexLazyRoute
  '/_teacher/teacher-dashboard/subject-offering/$subjectId': typeof TeacherTeacherDashboardSubjectOfferingSubjectIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/teacher-dashboard/attendance'
    | '/teacher-dashboard/class-schedule'
    | '/teacher-dashboard/subject'
    | '/student-dashboard'
    | '/teacher-dashboard'
    | '/teacher-dashboard/subject-offering/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/teacher-dashboard/attendance'
    | '/teacher-dashboard/class-schedule'
    | '/teacher-dashboard/subject'
    | '/student-dashboard'
    | '/teacher-dashboard'
    | '/teacher-dashboard/subject-offering/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/_teacher'
    | '/login'
    | '/_teacher/teacher-dashboard/attendance'
    | '/_teacher/teacher-dashboard/class-schedule'
    | '/_teacher/teacher-dashboard/subject'
    | '/_student/student-dashboard/'
    | '/_teacher/teacher-dashboard/'
    | '/_teacher/teacher-dashboard/subject-offering/$subjectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_student",
        "/_teacher",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_student": {
      "filePath": "_student.tsx",
      "children": [
        "/_student/student-dashboard/"
      ]
    },
    "/_teacher": {
      "filePath": "_teacher.tsx",
      "children": [
        "/_teacher/teacher-dashboard/attendance",
        "/_teacher/teacher-dashboard/class-schedule",
        "/_teacher/teacher-dashboard/subject",
        "/_teacher/teacher-dashboard/",
        "/_teacher/teacher-dashboard/subject-offering/$subjectId"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_teacher/teacher-dashboard/attendance": {
      "filePath": "_teacher/teacher-dashboard/attendance.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_teacher/teacher-dashboard/class-schedule": {
      "filePath": "_teacher/teacher-dashboard/class-schedule.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_teacher/teacher-dashboard/subject": {
      "filePath": "_teacher/teacher-dashboard/subject.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_student/student-dashboard/": {
      "filePath": "_student/student-dashboard/index.lazy.tsx",
      "parent": "/_student"
    },
    "/_teacher/teacher-dashboard/": {
      "filePath": "_teacher/teacher-dashboard/index.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_teacher/teacher-dashboard/subject-offering/$subjectId": {
      "filePath": "_teacher/teacher-dashboard/subject-offering/$subjectId.lazy.tsx",
      "parent": "/_teacher"
    }
  }
}
ROUTE_MANIFEST_END */
