/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeacherImport } from './routes/_teacher'
import { Route as StudentImport } from './routes/_student'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TeacherTeacherDashboardLazyImport = createFileRoute(
  '/_teacher/teacher-dashboard',
)()
const StudentStudentDashboardLazyImport = createFileRoute(
  '/_student/student-dashboard',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const TeacherRoute = TeacherImport.update({
  id: '/_teacher',
  getParentRoute: () => rootRoute,
} as any)

const StudentRoute = StudentImport.update({
  id: '/_student',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeacherTeacherDashboardLazyRoute =
  TeacherTeacherDashboardLazyImport.update({
    path: '/teacher-dashboard',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher.teacher-dashboard.lazy').then((d) => d.Route),
  )

const StudentStudentDashboardLazyRoute =
  StudentStudentDashboardLazyImport.update({
    path: '/student-dashboard',
    getParentRoute: () => StudentRoute,
  } as any).lazy(() =>
    import('./routes/_student.student-dashboard.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentImport
      parentRoute: typeof rootRoute
    }
    '/_teacher': {
      id: '/_teacher'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TeacherImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_student/student-dashboard': {
      id: '/_student/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof StudentStudentDashboardLazyImport
      parentRoute: typeof StudentImport
    }
    '/_teacher/teacher-dashboard': {
      id: '/_teacher/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof TeacherTeacherDashboardLazyImport
      parentRoute: typeof TeacherImport
    }
  }
}

// Create and export the route tree

interface StudentRouteChildren {
  StudentStudentDashboardLazyRoute: typeof StudentStudentDashboardLazyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentDashboardLazyRoute: StudentStudentDashboardLazyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherTeacherDashboardLazyRoute: typeof TeacherTeacherDashboardLazyRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherTeacherDashboardLazyRoute: TeacherTeacherDashboardLazyRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student-dashboard': typeof StudentStudentDashboardLazyRoute
  '/teacher-dashboard': typeof TeacherTeacherDashboardLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/student-dashboard': typeof StudentStudentDashboardLazyRoute
  '/teacher-dashboard': typeof TeacherTeacherDashboardLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_student': typeof StudentRouteWithChildren
  '/_teacher': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_student/student-dashboard': typeof StudentStudentDashboardLazyRoute
  '/_teacher/teacher-dashboard': typeof TeacherTeacherDashboardLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/login' | '/student-dashboard' | '/teacher-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/student-dashboard' | '/teacher-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/_teacher'
    | '/login'
    | '/_student/student-dashboard'
    | '/_teacher/teacher-dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_student",
        "/_teacher",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_student": {
      "filePath": "_student.tsx",
      "children": [
        "/_student/student-dashboard"
      ]
    },
    "/_teacher": {
      "filePath": "_teacher.tsx",
      "children": [
        "/_teacher/teacher-dashboard"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_student/student-dashboard": {
      "filePath": "_student.student-dashboard.lazy.tsx",
      "parent": "/_student"
    },
    "/_teacher/teacher-dashboard": {
      "filePath": "_teacher.teacher-dashboard.lazy.tsx",
      "parent": "/_teacher"
    }
  }
}
ROUTE_MANIFEST_END */
