/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeacherImport } from './routes/_teacher'
import { Route as StudentImport } from './routes/_student'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const IndexLazyImport = createFileRoute('/')()
const TeacherDashboardIndexLazyImport = createFileRoute(
  '/_teacher/dashboard/',
)()
const StudentDashboardIndexLazyImport = createFileRoute(
  '/_student/dashboard/',
)()
const TeacherDashboardClassScheduleLazyImport = createFileRoute(
  '/_teacher/dashboard/class-schedule',
)()
const TeacherDashboardAttendanceLazyImport = createFileRoute(
  '/_teacher/dashboard/attendance',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const TeacherRoute = TeacherImport.update({
  id: '/_teacher',
  getParentRoute: () => rootRoute,
} as any)

const StudentRoute = StudentImport.update({
  id: '/_student',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeacherDashboardIndexLazyRoute = TeacherDashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => TeacherRoute,
} as any).lazy(() =>
  import('./routes/_teacher/dashboard/index.lazy').then((d) => d.Route),
)

const StudentDashboardIndexLazyRoute = StudentDashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => StudentRoute,
} as any).lazy(() =>
  import('./routes/_student/dashboard/index.lazy').then((d) => d.Route),
)

const TeacherDashboardClassScheduleLazyRoute =
  TeacherDashboardClassScheduleLazyImport.update({
    path: '/dashboard/class-schedule',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/dashboard/class-schedule.lazy').then(
      (d) => d.Route,
    ),
  )

const TeacherDashboardAttendanceLazyRoute =
  TeacherDashboardAttendanceLazyImport.update({
    path: '/dashboard/attendance',
    getParentRoute: () => TeacherRoute,
  } as any).lazy(() =>
    import('./routes/_teacher/dashboard/attendance.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentImport
      parentRoute: typeof rootRoute
    }
    '/_teacher': {
      id: '/_teacher'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TeacherImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_teacher/dashboard/attendance': {
      id: '/_teacher/dashboard/attendance'
      path: '/dashboard/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof TeacherDashboardAttendanceLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_teacher/dashboard/class-schedule': {
      id: '/_teacher/dashboard/class-schedule'
      path: '/dashboard/class-schedule'
      fullPath: '/dashboard/class-schedule'
      preLoaderRoute: typeof TeacherDashboardClassScheduleLazyImport
      parentRoute: typeof TeacherImport
    }
    '/_student/dashboard/': {
      id: '/_student/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudentDashboardIndexLazyImport
      parentRoute: typeof StudentImport
    }
    '/_teacher/dashboard/': {
      id: '/_teacher/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof TeacherDashboardIndexLazyImport
      parentRoute: typeof TeacherImport
    }
  }
}

// Create and export the route tree

interface StudentRouteChildren {
  StudentDashboardIndexLazyRoute: typeof StudentDashboardIndexLazyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardIndexLazyRoute: StudentDashboardIndexLazyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherDashboardAttendanceLazyRoute: typeof TeacherDashboardAttendanceLazyRoute
  TeacherDashboardClassScheduleLazyRoute: typeof TeacherDashboardClassScheduleLazyRoute
  TeacherDashboardIndexLazyRoute: typeof TeacherDashboardIndexLazyRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherDashboardAttendanceLazyRoute: TeacherDashboardAttendanceLazyRoute,
  TeacherDashboardClassScheduleLazyRoute:
    TeacherDashboardClassScheduleLazyRoute,
  TeacherDashboardIndexLazyRoute: TeacherDashboardIndexLazyRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/attendance': typeof TeacherDashboardAttendanceLazyRoute
  '/dashboard/class-schedule': typeof TeacherDashboardClassScheduleLazyRoute
  '/dashboard': typeof TeacherDashboardIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/attendance': typeof TeacherDashboardAttendanceLazyRoute
  '/dashboard/class-schedule': typeof TeacherDashboardClassScheduleLazyRoute
  '/dashboard': typeof TeacherDashboardIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_student': typeof StudentRouteWithChildren
  '/_teacher': typeof TeacherRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/_teacher/dashboard/attendance': typeof TeacherDashboardAttendanceLazyRoute
  '/_teacher/dashboard/class-schedule': typeof TeacherDashboardClassScheduleLazyRoute
  '/_student/dashboard/': typeof StudentDashboardIndexLazyRoute
  '/_teacher/dashboard/': typeof TeacherDashboardIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/class-schedule'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/class-schedule'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/_teacher'
    | '/login'
    | '/_teacher/dashboard/attendance'
    | '/_teacher/dashboard/class-schedule'
    | '/_student/dashboard/'
    | '/_teacher/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_student",
        "/_teacher",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_student": {
      "filePath": "_student.tsx",
      "children": [
        "/_student/dashboard/"
      ]
    },
    "/_teacher": {
      "filePath": "_teacher.tsx",
      "children": [
        "/_teacher/dashboard/attendance",
        "/_teacher/dashboard/class-schedule",
        "/_teacher/dashboard/"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_teacher/dashboard/attendance": {
      "filePath": "_teacher/dashboard/attendance.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_teacher/dashboard/class-schedule": {
      "filePath": "_teacher/dashboard/class-schedule.lazy.tsx",
      "parent": "/_teacher"
    },
    "/_student/dashboard/": {
      "filePath": "_student/dashboard/index.lazy.tsx",
      "parent": "/_student"
    },
    "/_teacher/dashboard/": {
      "filePath": "_teacher/dashboard/index.lazy.tsx",
      "parent": "/_teacher"
    }
  }
}
ROUTE_MANIFEST_END */
