export const users = [
  {
    name: "Subik Shrestha",
    username: "subikstha",
    password: "Xenos@777",
    email: "subsatch@gmail.com",
    role: "teacher",
  },
  {
    name: "Ayush Chalise",
    firstName: "Ayush",
    lastName: "Chalise",
    username: "ayushChalise",
    password: "Student@123",
    email: "ayush@gmail.com",
    role: "student",
  },
  {
    name: "Aman Sarfraj",
    firstName: "Aman",
    lastName: "Sarfraj",
    username: "amanSarfraj",
    password: "Student@123",
    email: "aman@gmail.com",
    role: "student",
  },
  {
    name: "Birajman Yadav",
    firstName: "Birajman",
    lastName: "Yadav",
    username: "birajmanYadav",
    password: "Student@123",
    email: "birajman@gmail.com",
    role: "student",
  },
  {
    name: "Ganga Pandeya",
    firstName: "Ganga",
    lastName: "Pandeya",
    username: "gangaPandeya",
    password: "Student@123",
    email: "ganga@gmail.com",
    role: "student",
  },
  {
    name: "Kridisna Nepal",
    firstName: "Kridisna",
    lastName: "Nepal",
    username: "kridisnaNepal",
    password: "Student@123",
    email: "kridisna@gmail.com",
    role: "student",
  },
  {
    name: "Kristina Awale",
    firstName: "Kristina",
    lastName: "Awale",
    username: "kristinaAwale",
    password: "Student@123",
    email: "kristina@gmail.com",
    role: "student",
  },
  {
    name: "Milan Neupane",
    firstName: "Milan",
    lastName: "Neupane",
    username: "milanNeupane",
    password: "Student@123",
    email: "milan@gmail.com",
    role: "student",
  },
  {
    name: "Neha Kumari Pariyar",
    firstName: "Neha Kumari",
    lastName: "Pariyar",
    username: "nehaKumariPariyar",
    password: "Student@123",
    email: "neha@gmail.com",
    role: "student",
  },
  {
    name: "Roshani Yadav",
    firstName: "Roshani",
    lastName: "Yadav",
    username: "roshaniYadav",
    password: "Student@123",
    email: "roshani@gmail.com",
    role: "student",
  },
  {
    name: "Saugat Nepal",
    firstName: "Saugat",
    lastName: "Nepal",
    username: "saugatNepal",
    password: "Student@123",
    email: "saugat@gmail.com",
    role: "student",
  },
  {
    name: "Sheela Khatri",
    firstName: "Sheela",
    lastName: "Khatri",
    username: "sheelaKhatri",
    password: "Student@123",
    email: "sheela@gmail.com",
    role: "student",
  },
];
